name: iOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/HowToSwift.app

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies

    - name: Build
      run: |
        set -o pipefail
        xcodebuild \
          -scheme HowToSwift \
          -project HowToSwift.xcodeproj \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          build-for-testing
